#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# Last modified: 2018-11-14
import sys, os
import papis.api
import papis.cli
from papis.commands.open import run as papis_open
import papis.database
import click


@click.command()
@click.help_option('-h', '--help')
@papis.cli.query_option()
def main(query):
    """
    Search tags of the library and open a document
    """
    documents = papis.api.get_documents_in_lib(
        papis.api.get_lib(),
        search=query
    )

    picked_tags = set()
    
    while True:
        # Create an empty tag list
        tag_list = []
        matching_documents = 0
        for item in documents:
            if 'tags' in item.keys():
                tags = item['tags']
                if isinstance(tags, list):
                    tags = ",".join(tags)
                # clean the tag(s)
                tags = [tag.strip(' ').lower() for tag in tags.split(',')]
                if picked_tags.issubset(tags):
                    matching_documents = matching_documents + 1
                    tag_list.extend(tags)
        # if no tags are found, exit gracefully
        if tag_list == []:
            print('The library does not have any tags set')
            return

        annotated_tag_list = ["* Any tag (" + str(matching_documents) + ")"] + \
            [tag + " (" + str(tag_list.count(tag)) + ")"
             for tag in sorted(set(tag_list) - picked_tags)]

        picked_tag = papis.api.pick(annotated_tag_list)
        if not picked_tag:
            return
        matches = picked_tag[picked_tag.rindex('(')+1:-1]
        picked_tag = picked_tag[:picked_tag.rindex('(')-1]
        if picked_tag == "* Any tag":
            break
        picked_tags.add(picked_tag)
        if int(matches) == 1:
            break

    query_string = " ".join(
            ["tags=\"{}\" ".format(tag) for tag in picked_tags]
        )
    docs = papis.database.get().query(query_string)
    doc = papis.api.pick_doc(docs)
    if not doc:
        return

    papis_open(doc)


if __name__ == "__main__":
    main()
